#!/usr/bin/env python3
"""One-off: emit content/publications.yml from the baseline HTML and CV LaTeX.

Nothing is retyped. Abstracts, link rows, awards and commentary come straight
out of the baseline; author lists and volume/issue/pages come out of the CV.
Where the two sources disagree the site wins, because the BibTeX agrees with it
on every one of the six conflicts -- the CV was simply never updated.

Safe to delete once content/publications.yml is settled.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup

BASE = Path("tests/acceptance/baseline")
ICON_LABEL = {}


def yq(s: str) -> str:
    """Quote a YAML scalar."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", (s or "").lower())


def cv_index():
    """CV \\items, keyed by PDF basename AND by normalized title.

    The basename is the better key when both sides link the same offprint, but
    roughly half the CV entries link the journal instead, so title matching is
    needed too. The CV's author lists are the authoritative ones: BibTeX
    truncates them (Science's export gives 11 names for a paper with 25).
    """
    tex = (BASE / "GraemeBlair-CV.tex").read_text(encoding="utf-8")
    out = {}
    for block in re.findall(r"\\begin{etaremune}(.*?)\\end{etaremune}", tex, re.S):
        for item in re.split(r"\n\s*\\item ", block)[1:]:
            item = item.strip()
            m = re.search(r"\\href{([^}]*)}", item)
            if m:
                out[m.group(1).rsplit("/", 1)[-1]] = item
            t = re.search(r"``(.+?)(?:\'\'|\")", item, re.S)
            if t:
                out["T:" + _norm(t.group(1))] = item
    return out


def parse_authors(item: str) -> tuple[list[str], str | None]:
    """Author run before the title, plus the volume/issue/pages tail.

    Split on the opening `` of the title rather than on a year: forthcoming
    papers have no year, and splitting on one silently swallowed the title into
    the author list.
    """
    body = re.sub(r"\\href{[^}]*}{", "", item)
    head = body.split("``", 1)[0]
    head = re.sub(r"\\textcircled\{r\}|\\textit|[{}\\*]", "", head)
    head = re.sub(r"\b(?:19|20)\d\d\.?\s*$", "", head.strip()).strip().rstrip(".")
    parts = re.split(r",\s*and\s+|\s+and\s+|,\s*|\s*Ⓡ\s*|\s*\u24C7\s*", head)
    tail = re.search(r"\{\\it [^}]*\}\s*([0-9(),:\s\u2013-]+)", item)
    return [a.strip(" .") for a in parts if a.strip(" .")], (tail.group(1).strip(" .") if tail else None)


def main():
    soup = BeautifulSoup((BASE / "index.html").read_text(encoding="utf-8"), "lxml")
    cv = cv_index()
    print("# Generated by tools/emit_publications.py -- review before trusting.")
    print("publications:")

    for col in soup.select("#research > .row > div"):
        heading = col.find("h1")
        column = "policing" if "Policing" in heading.get_text() else "methods"
        for p in col.select("p.paper-title, p.book-title"):
            text = p.get_text(" ", strip=True)
            if text.startswith("Commentary"):
                continue
            toggle = p.select_one("[data-bs-target]")
            slug = toggle["data-bs-target"].lstrip("#")[: -len("Abstract")] if toggle else None
            panel = soup.select_one(f'div[id="{slug}Abstract"]') if slug else None

            title = re.match(r"[“\"](.+?)[”\"]", text)
            title = title.group(1) if title else text.split(".")[0]
            venue = p.find("b")
            year = re.search(r"\b(19|20)\d\d\b", text)

            print(f"  - slug: {slug}")
            print(f"    title: {yq(title)}")
            if venue:
                print(f"    venue: {yq(venue.get_text(strip=True))}")
            if year:
                print(f"    year: {year.group(0)}")
            print(f"    column: {column}")

            pdf = None
            if panel:
                for a in panel.select("p.paper-links a"):
                    if a.get("data-citation"):
                        print(f"    cite: {a['data-citation']}")
                    href = a.get("href") or ""
                    if href.endswith(".pdf") and "papers/" in href:
                        pdf = href.rsplit("/", 1)[-1]
                item = cv.get(pdf) if pdf else None
                if item is None:
                    # Fall back to title, tolerating the sentence/Title-case and
                    # wording differences between the two sources.
                    import difflib
                    keys = [k for k in cv if k.startswith("T:")]
                    best = difflib.get_close_matches("T:" + _norm(title), keys, 1, 0.75)
                    item = cv[best[0]] if best else None
                if item is not None:
                    authors, tail = parse_authors(item)
                    print(f"    authors: [{', '.join(yq(a) for a in authors)}]")
                    if tail:
                        print(f"    cv_detail: {yq(tail)}")
                links = []
                for a in panel.select("p.paper-links a"):
                    if a.get("data-citation"):
                        links.append("      - {label: Cite}")
                    else:
                        icon = a.find("i")
                        label = a.get_text(strip=True)
                        ICON_LABEL.setdefault(label, " ".join(icon.get("class", [])) if icon else "")
                        links.append(f"      - {{label: {yq(label)}, url: {yq(a['href'])}}}")
                if links:
                    print("    links:")
                    print("\n".join(links))
                for a in panel.select("p > a"):
                    if a.find("i", class_="fa-trophy"):
                        print(f"    award: {{text: {yq(a.get_text(strip=True))}, url: {yq(a['href'])}}}")
                ab = panel.select_one("p.abstracttext")
                if ab:
                    # Wrap on word boundaries. A YAML folded scalar joins lines
                    # with a space, so breaking mid-word would insert one inside
                    # the word.
                    import textwrap
                    print("    abstract: >-")
                    for line in textwrap.wrap(ab.get_text(" ", strip=True), 92):
                        print("      " + line)
            print()

    print("# icon table observed in the baseline:", file=sys.stderr)
    for label, icon in sorted(ICON_LABEL.items()):
        print(f"#   {label:20} {icon}", file=sys.stderr)


if __name__ == "__main__":
    main()
